version: '3.8'

# ============================================
# Stack para Portainer - Observabilidade IT
# ============================================
# Como usar:
# 1. No Portainer, vá em Stacks > Add Stack
# 2. Cole este conteúdo ou faça upload do arquivo
# 3. Configure as variáveis de ambiente abaixo
# 4. Deploy!

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-observabilidade}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-observabilidade}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-observabilidade}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal

  # Redis
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal

  # API Backend
  api:
    image: ghcr.io/${GITHUB_USER:-seu-usuario}/observabilidade-api:latest
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgresql://${POSTGRES_USER:-observabilidade}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-observabilidade}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:?Defina JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - EMAIL_FROM=${EMAIL_FROM:-onboarding@resend.dev}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - internal

  # Worker (Monitor Checks)
  worker:
    image: ghcr.io/${GITHUB_USER:-seu-usuario}/observabilidade-api:latest
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: node dist/workers/monitor-check.worker.js
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-observabilidade}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-observabilidade}
      - REDIS_URL=redis://redis:6379
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - EMAIL_FROM=${EMAIL_FROM:-onboarding@resend.dev}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal

  # Frontend Next.js
  web:
    image: ghcr.io/${GITHUB_USER:-seu-usuario}/observabilidade-web:latest
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-/api}
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - internal

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  internal:
    driver: bridge
